# Path to the data folder. Data should be separated into train.npy, train_label.npy, val.npy, val_label.npy.
data_folder: "D:/OtherGitProject/deep-contact-estimator/data\\numpy/"

# Path to save the trained model. 
# Please leave the filename extension out.
# It will automatically generate ${name}_best_loss.pt, ${name}_best_acc.pt, ${name}_final_epo.pt.
model_save_path: "D:/OtherGitProject/deep-contact-estimator/data\\model/"
log_writer_path: "D:/OtherGitProject/deep-contact-estimator/data/log/"


model_description: "1D CNN 2block, 54-64-64-drop-pool-128-128-drop-pool-fc, shuffle train, batch: 30, ws:150, lr:1e-4, all data"

print_every: 1000

# Data params
window_size: 150
shuffle: True

# Network params
batch_size: 30
init_lr: 0.0001
num_epoch: 30


